apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cb-default-sc
parameters:
  type: gp2
  fsType: ext4
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true